### ISSUE TITLE
Xcode 11.4

### ISSUE THREAD

**Issue by alv-ti8m** [aidantwoods/swift-paseto#8]
Hi, I'm using your library on a swift project, and starting from Xcode 11.4 it does not build anymore. Xcode always complain about "circular references" on Local and Public. Do you still support this project? Could you have a look and fix it?

**Comment by aidantwoods** [comment]
Thanks for the heads up :) I'll take a look later today

**Comment by aidantwoods** [comment]
Can you give 0.2.1 a go? This should now be fixed :)

**Comment by alv-ti8m** [comment]
Hi Aidan. it works like a charm.
Thanks very much for your effort!
